INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092059', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092059', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'HRO Approval', 'HR Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092059', 'HRO Approval', 'HR Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'Candidate registration ', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092074', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092055', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092055', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092040', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092040', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092040', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092045', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092045', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092045', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092040', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092040', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092040', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092040', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092040', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092040', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092045', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092045', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092015', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092015', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092015', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092015', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092015', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092045', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092045', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092045', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092045', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092015', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092015', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092015', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092015', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('000000', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('000000', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('000000', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('000000', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('000000', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('000000', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('000000', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123456', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123456', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123456', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123333', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123333', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123333', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123333', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123333', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123456', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123456', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123456', 'HRO Approval', 'HR Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('222222', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('222222', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('222222', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123456', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123456', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123456', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('123456', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('222222', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('222222', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092067', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092077', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('777777', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('777777', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('777777', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('777777', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('777777', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092015', 'HRO Approval', 'HR Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092090', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092090', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092090', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092090', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092090', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092023', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092023', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092023', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092023', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092023', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092080', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092050', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092050', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092050', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092050', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('092050', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('093067', 'Candidate Registration', 'Registered');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('093067', 'Application Recevied', 'Application Recevied');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('093067', 'Modification', 'Student cant modify data');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('093067', 'Upload resume', 'Yes');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('093067', 'TPO Approval', 'TPO Approved');
INSERT INTO `activity_status_box` (`StudentId`, `Activity`, `Status`) VALUES ('093067', 'Congratulation for Placement', 'Plz confirmed yor PLacement');
